name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ] # Or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 25.6.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Restore Dist Cache
        uses: actions/cache@v5
        with:
          path: dist
          # We use a static key so it always tries to find the most recent dist
          key: ${{ runner.os }}-dist-cache-${{ github.run_id }}
          # This is the "magic" part: it finds the most recent cache starting with this prefix
          restore-keys: |
            ${{ runner.os }}-dist-cache-

      - name: Build project
        run: pnpm run build # This runs your build.js

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=xad
